/** Full YAML example for POST /source-connections/import-yaml (must stay in sync with backend FIELD_SPECS). */
export const YAML_SOURCE_IMPORT_TEMPLATE = [
    "# Airweave bulk source import — version must be 1.",
    "# Layout: sources.<source_type>.<connection_display_name>: { ...credentials and config... }",
    "# Supported types: github, gitlab, local_git, dingtalk, confluence",
    "# Replace env-style placeholders and paths/URLs before Validate / Import.",
    "",
    "version: 1",
    "",
    "sources:",
    "  github:",
    "    Example GitHub:",
    "      personal_access_token: ${GITHUB_PAT}",
    "      repo_name: owner/repository",
    "      branch: main",
    "      sync_pull_requests: false",
    "",
    "  gitlab:",
    "    Example GitLab:",
    "      personal_access_token: ${GITLAB_TOKEN}",
    "      repo_url: https://gitlab.com/group/project.git",
    "      branch: main",
    "",
    "  local_git:",
    "    Example Local Git:",
    "      repo_path: /absolute/path/to/git/repository",
    "      branch: main",
    "      follow_symlinks: false",
    "",
    "  dingtalk:",
    "    Example DingTalk Docs:",
    "      app_key: ${DINGTALK_APP_KEY}",
    "      app_secret: ${DINGTALK_APP_SECRET}",
    '      links: "https://alidocs.dingtalk.com/i/nodes/your-doc-or-wiki-link"',
    "      operator_union_id: ${DINGTALK_OPERATOR_UNION_ID}",
    "",
    "  confluence:",
    "    Example Confluence:",
    "      personal_access_token: ${CONFLUENCE_API_TOKEN}",
    "      site_url: https://your-domain.atlassian.net",
].join("\n");

export const YAML_SOURCE_IMPORT_TEMPLATE_FILENAME = "airweave-sources-import-template.yaml";
